/**
    @author Jatin Narula
 * PURPOSE: Its a global utility class, it should be used for all the ARR related services.
 * We MUST NOT add any redundent code to any other class, if a developer feels to create a reusable method related to ARR, they should create it here.
 * In case of questions reach out to author of this class.
 *
 * TEST COVERAGE: OliUtility_Test
 *
 * BIZSYS-26212
 *
 * CHANGELOG (for major changes) - dd-mm-yyyy
 * 17-01-2022           Jatin Narula              Created.
 * 02-16-2022           Jarrod Hinson             BIZSYS-30088 updated for Rollover Changes.

 */
public class OliUtility{
}